### ISSUE TITLE
failure when I try to use it as substitude indexer in Jina-examples

### ISSUE THREAD

**Issue by TITC** [jina-ai/executor-faissindexer#11]
Here are excerpts described at[ this example](https://github.com/jina-ai/examples/tree/master/wikipedia-sentences)
> It is then recommended to use more advanced indexers like the FaissIndexer.

But when I replace[ this part](https://github.com/jina-ai/examples/blob/36c9bf2798d54cad34aa47bb4c0be290985b7396/wikipedia-sentences/flows/flow.yml#L9-L10) with instruction in [Jina-hub](https://hub.jina.ai/executor/8gsd0tts)
```python
from jina import Flow

f = Flow().add(uses='jinahub+docker://FaissIndexer/v0.1')
```

from 
```
  - name: indexer                                     # Now, index the text documents with the embeddings
    uses: 'jinahub://SimpleIndexer/old'                   # We use the SimpleIndexer for this purpose
```
to
```
  - name: indexer                                     # Now, index the text documents with the embeddings
    uses: 'jinahub+docker://FaissIndexer/v0.1'                   # We use the SimpleIndexer for this purpose
```

Although it's haven't any error messages, but not work. what's wrong with it? What's the proper manner to use it?

**Comment by numb3r3** [comment]
@TITC Thanks for your feedback. Could you test the latest one `jinahub+docker://FaissIndexer/v0.2`

**Comment by numb3r3** [comment]
> it's haven't any error messages, but not work

BTW, what is the meaning of **not work**?. It cannot return any result?

**Comment by TITC** [comment]
> > it's haven't any error messages, but not work
> 
> BTW, what is the meaning of **not work**?. It cannot return any result?
thanks for your response, I have tried both 1.0 and 2.0 versions.

1. query without result
2. haven't any serialization files generated by indexer like `xxx.bin` or folder name `workspace`
3. work normally when using `'jinahub://SimpleIndexer/old' `  and that will generate a folder name `workspace`

**Comment by TITC** [comment]
>Have you install all dependencies for using FaissIndexer?

[All of the dependencies](https://hub.jina.ai/executor/8gsd0tts) listed below have been installed and I just verified again.
![image](https://user-images.githubusercontent.com/35098797/137898202-735132a9-42df-48cc-bf9e-487480c12224.png)

>You can install requirements via .add(uses='jinahub://FaissIndexer/v0.2', install_requirments=True)

here is what I have done before and reproduce it one more time. comment the indexer in the `yml` file
```yml
jtype: Flow                                           # This file defines the flow (both index and query) for the wikipedia sentences example
version: '1'                                          # This is the yml file version
with:                                                 # Additional arguments for the flow
  workspace: $JINA_WORKSPACE                          # Workspace folder path
  port_expose: $JINA_PORT                             # Network Port for the flow
executors:                                            # Now, define the executors that are run on this flow
  - name: transformer                                 # This executor computes an embedding based on the input text documents
    uses: 'jinahub+docker://TransformerTorchEncoder/v0.1'  # We use a Transformer Torch Encoder from the hub as a docker container
  # - name: indexer                                     # Now, index the text documents with the embeddings
  #   uses: 'jinahub://FaissIndexer/v0.2'                   # We use the SimpleIndexer for this purpose
```
and add executor to flow
```python
def index(num_docs):
    flow = Flow().load_config('flows/flow.yml').add(uses='jinahub://FaissIndexer/v0.2', install_requirments=True)
    data_path = os.path.join(os.path.dirname(
        __file__), os.environ.get('JINA_DATA_FILE', None))
    with flow:
        flow.post(on='/index', inputs=input_generator(num_docs, data_path),
                  show_progress=True)


def query(top_k):
    flow = Flow().load_config('flows/flow.yml').add(uses='jinahub://FaissIndexer/v0.2', install_requirments=True)
```
still not work
```shell
⏳   |█                   | ⏱️ 0.0s 🐎 0.0 RPS           pod1@58632[E]:AttributeError("'DocumentArray' object has no attribute 'embeddings'")
 add "--quiet-error" to suppress the exception details
```
> the Jina version in the examples(2.0.18) is a little bit outdated, you can update Jina to a newer version. Try using Jina 2.1.7 

then `pip install -U jina`, it's work. Thanks for your help X) @Hippopotamus0308
